[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo", "php82Extensions.pdo_mysql", "php82Extensions.mbstring", "php82Extensions.xml", "php82Extensions.curl", "nodejs_20", "composer"]

[phases.build]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "npm install",
    "npm run build",
    "php artisan config:cache",
    "php artisan route:cache"
]

[phases.release]
cmds = ["php artisan migrate --force --seed"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"